<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-6HTCB4G" ignored="2" name="Default test(failed)" tests="5" failures="1" timestamp="11 Nov 2021 04:49:41 GMT" time="41.059" errors="0">
  <testcase name="testA2" time="3.798" classname="org.run.Rerun">
    <skipped/>
  </testcase> <!-- testA2 -->
  <testcase name="testA2" time="2.293" classname="org.run.Rerun">
    <skipped/>
  </testcase> <!-- testA2 -->
  <testcase name="testA2" time="18.966" classname="org.run.Rerun">
    <skipped/>
  </testcase> <!-- testA2 -->
  <testcase name="testA2" time="10.871" classname="org.run.Rerun">
    <skipped/>
  </testcase> <!-- testA2 -->
  <testcase name="testA2" time="1.207" classname="org.run.Rerun">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	invalid username expected [Arun] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
invalid username expected [Arun] but found [true]
at org.run.Rerun.testA2(Rerun.java:44)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testA2 -->
  <testcase name="testA3" time="0.0" classname="org.run.Rerun">
    <ignored/>
  </testcase> <!-- testA3 -->
  <testcase name="testA1" time="0.0" classname="org.run.Rerun">
    <ignored/>
  </testcase> <!-- testA1 -->
</testsuite> <!-- Default test(failed) -->
